version: 2.1
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
jobs:
   print-hello:
      docker:
         - image: circleci/node:13.8.0
           auth:
             username: mydockerhub-user
             password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
         - run: echo "Hello"
   print-world:
      docker:
         - image: circleci/node:13.8.0
           auth:
             username: mydockerhub-user
             password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
         - run: echo "World"
workflows:
   my-workflow:
      jobs:
         - welcome/run
         - print-hello
         - print-world:
              requires:
                - print-world
         
