version: 2.1

jobs: 
  create_infrastructure: 
    docker: 
      - 
        image: amazon/aws-cli
    steps: 
      - checkout
      - 
        run: 
          command: |
              pwd
              ls -la
              aws cloudformation deploy \
                --template-file circleci/template.yml \
                --stack-name my-stack
          name: "Ensure backend infrastructure exist"
workflows: 
  my_workflow: 
    jobs: 
      - create_infrastructure